### ISSUE TITLE
训练到1720iter时报错

### ISSUE THREAD

**Issue by ck6698000** [CityU-AIM-Group/SIGMA#34]
我又来打扰各位作者了哈哈，这次问题是这样的
Traceback (most recent call last):
  File "tools/train_net_da.py", line 726, in <module>
    main()
  File "tools/train_net_da.py", line 715, in main
    MODEL = train(cfg, args.local_rank, args.distributed, args.test_only,args.use_tensorboard)
  File "tools/train_net_da.py", line 601, in train
    meters,
  File "/home/e401/Desktop/wrs/projects/SIGMA/fcos_core/engine/trainer.py", line 299, in do_train
    model, (images_s, images_t), targets=targets_s, return_maps=True)
  File "/home/e401/Desktop/wrs/projects/SIGMA/fcos_core/engine/trainer.py", line 69, in foward_detector
    (features_s, features_t), middle_head_loss = model_middle_head(images, (features_s,features_t), targets=targets, score_maps=score_maps )
  File "/home/e401/anaconda3/envs/SIGMA/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/e401/Desktop/wrs/projects/SIGMA/fcos_core/modeling/rpn/fcos/graph_matching_head.py", line 229, in forward
    features, feat_loss = self._forward_train(images, features, targets, score_maps)
  File "/home/e401/Desktop/wrs/projects/SIGMA/fcos_core/modeling/rpn/fcos/graph_matching_head.py", line 348, in _forward_train
    matching_loss_quadratic = self._forward_qu(nodes_1, nodes_2, edges_1.detach(), edges_2.detach(), affinity)
  File "/home/e401/Desktop/wrs/projects/SIGMA/fcos_core/modeling/rpn/fcos/graph_matching_head.py", line 624, in _forward_qu
    sin2 = torch.sqrt(1.- F.cosine_similarity(triangle_2, triangle_2_tmp).pow(2)).sort()[0]
RuntimeError: The size of tensor a (8) must match the size of tensor b (9) at non-singleton dimension 0

其他信息：
1. 用的是自己的数据集
2. 同样的代码在另一个数据集下运行就没事
3. 报错前loss依然较平稳下降中
为何tensor维度会出问题呢，就感觉有点神奇

**Comment by wymanCV** [comment]
您好，非常感谢您对我们工作的关注！我们在benchmark数据集上没有遇到过这个问题，因此我推测有可能是某个样本存在标注错误，也有可能是我们这部分的实现不够鲁棒导致的，我们后续会尝试排查这个问题。目前您可以使用两个解决方案。1是您可以尝试添加一句这行代码在报错的语句之前，来暂时忽略当前迭代：
```
if triangle_2.size() != triangle_2_tmp.size():
    return triangle_2.sum() * 0.
```

2是您也可以通过设置False关闭超边匹配

https://github.com/CityU-AIM-Group/SIGMA/blob/0d2894ce66769430bb8d63024d11da5d21eb91f5/configs/sigma_plus_plus/city_to_bdd100k_vgg16.yaml#L33

**Comment by ck6698000** [comment]
> 您好，非常感谢您对我们工作的关注！我们在benchmark数据集上没有遇到过这个问题，因此我推测有可能是某个样本存在标注错误，也有可能是我们这部分的实现不够鲁棒导致的，我们后续会尝试排查这个问题。目前您可以使用两个解决方案。1是您可以尝试添加一句这行代码在报错的语句之前，来暂时忽略当前迭代：
> 
> ```
> if triangle_2.size() != triangle_2_tmp.size():
>     return triangle_2.sum() * 0.
> ```
> 
> 2是您也可以通过设置False关闭超边匹配
> 
> https://github.com/CityU-AIM-Group/SIGMA/blob/0d2894ce66769430bb8d63024d11da5d21eb91f5/configs/sigma_plus_plus/city_to_bdd100k_vgg16.yaml#L33

好的 非常感谢~
