### ISSUE TITLE
Error with accimage

### ISSUE THREAD

**Issue by ShenZheng2000** [CityU-AIM-Group/SIGMA#37]
I am running Python version 3.8.10 with torch version '1.9.0+cu111' and torchvision version 0.2.1. I installed additional packages as instructed in the [INSTALL.md](https://github.com/CityU-AIM-Group/SIGMA/blob/main/docs/INSTALL.md) file. 

Despite this, upon testing, I encountered the following error message.

```
2023-04-12 10:52:45,419 fcos_core.inference INFO: Start evaluation on cityscapes_foggy_val_cocostyle dataset(500 images).
  0%|                                                                                                                                                                            | 0/125 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test_net.py", line 112, in <module>
    main()
  File "tools/test_net.py", line 96, in main
    inference(
  File "/root/autodl-tmp/UDA/SIGMA/fcos_core/engine/inference.py", line 87, in inference
    predictions = compute_on_dataset(cfg, model, data_loader, device, inference_timer)
  File "/root/autodl-tmp/UDA/SIGMA/fcos_core/engine/inference.py", line 23, in compute_on_dataset
    for _, batch in enumerate(tqdm(data_loader)):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/UDA/SIGMA/fcos_core/data/datasets/coco.py", line 94, in __getitem__
    img, target = self.transforms(img, target)
  File "/root/autodl-tmp/UDA/SIGMA/fcos_core/data/transforms/transforms.py", line 15, in __call__
    image, target = t(image, target)
  File "/root/autodl-tmp/UDA/SIGMA/fcos_core/data/transforms/transforms.py", line 59, in __call__
    image = F.resize(image, size)
  File "/root/miniconda3/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 188, in resize
    if not _is_pil_image(img):
  File "/root/miniconda3/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 19, in _is_pil_image
    return isinstance(img, (Image.Image, accimage.Image))
AttributeError: module 'accimage' has no attribute 'Image'
```

The issue appears to stem from `accimage`, which is a pre-installed package in torchvision. This is unexpected because the version of torchvision being utilized is accurate.

**Comment by wymanCV** [comment]
Hi, thanks for your interest!

The package version in README.md is for 10.X CUDA. For CUDA 11.X, you have to install the latter pytorch and the corresponding matched torchvision, since the GPU doesn't support the old version. You can check this issue https://github.com/CityU-AIM-Group/SIGMA/issues/23

**Comment by ShenZheng2000** [comment]
I have managed to solve the problem by assigning accimage to None. I will closed this issue for now. 

![image](https://user-images.githubusercontent.com/69662345/231343486-75ed286e-ac66-4d8e-81ee-a194ec2ffe47.png)
